### ISSUE TITLE
The js0.23 modding community..

### ISSUE THREAD

**Issue by orphanlol** [RobinBoers/js0.23-improved#5]
do you chance to have a discord server for it?
also do you have a new link

**Comment by RobinBoers** [comment]
It's been years since I built this. I'm not in the Discord anymore, and I didn't interact much with other members anyway. Maybe you can ask the original developer? Looks like he goes by circuit10, and @Heath123 here on GitHub.

**Comment by Heath123** [comment]
https://discord.gg/2FCmWsMHrT
